listen: ":3000"
auth: true

timeouts:
  health_check: 5s
  proxy: 60s

redis:
  enabled: true
  uri: "redis://redis:6379/0"

rate_limit:
  enabled: true
  requests_per_second: 10
  burst: 20

networks:
  - name: pocket
    type: cosmos
    height_check:
      protocol: rpc
      interval: 30s
    endpoints:
      - protocol: rest
        listen: ":8080"
        advertise: "http://primary:8080"
      - protocol: rpc
        listen: ":8081"
        advertise: "http://primary:8081"
      - protocol: grpc
        listen: ":8082"
        advertise: "primary:8082"

internals:
  - name: seed-one
    network: pocket
    endpoints:
      rest: "https://api-seed-one.infra.pocket.network"
      rpc: "https://rpc-seed-one.infra.pocket.network"
      grpc: "grpc-seed-one.infra.pocket.network:443"

  - name: seed-two
    network: pocket
    endpoints:
      rest: "https://api-seed-two.infra.pocket.network"
      rpc: "https://rpc-seed-two.infra.pocket.network"
      grpc: "grpc-seed-two.infra.pocket.network:443"

externals:
  - name: secondary-ring
    token: "test-token-123"
    rings:
      - "http://secondary:4000"

users:
  - name: test-user
    token: "test-token-123"
    permissions: all
