api: true
rpc: true
grpc: true
auth: true
listen: ":3000"

timeouts:
  health_check: 5s
  proxy: 60s

redis:
  enabled: true
  uri: "redis://redis:6379/0"

rate_limit:
  enabled: true
  requests_per_second: 10
  burst: 20

networks:
  - name: "pocket"
    api: "http://primary:8080"
    api_listen: ":8080"
    rpc: "http://primary:8081"
    rpc_listen: ":8081"
    grpc: "primary:8082"
    grpc_listen: ":8082"
    grpc_insecure: true

internals:
  - name: seed-one
    api: "https://api-seed-one.infra.pocket.network"
    rpc: "https://rpc-seed-one.infra.pocket.network"
    grpc: "grpc-seed-one.infra.pocket.network:443"
    grpc_insecure: false
    network: "pocket"

  - name: seed-two
    api: "https://api-seed-two.infra.pocket.network"
    rpc: "https://rpc-seed-two.infra.pocket.network"
    grpc: "grpc-seed-two.infra.pocket.network:443"
    grpc_insecure: false
    network: "pocket"

externals:
  - name: secondary-ring
    token: "test-token-123"
    rings:
      - "http://secondary:4000"

users:
  - name: test-user
    token: "test-token-123"
    api: true
    rpc: true
    grpc: true
